name: db.migration.cicd
on:
  push:
    branches:
      - main

  workflow_dispatch:
   inputs:
    enableManualDeployement :
      description: 'Click to enable manual deployment from a custom branch to the test environment.'
      default: false
      required: true
      type: boolean

jobs:
  publish-test:
    name: deploy-test
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.enableManualDeployement == 'true' || github.ref == 'refs/heads/main' }}
    environment: 'test'
    steps:
      - uses: actions/checkout@v2
      - name: flyway info
        uses: ./.github/actions/flyway
        with: 
          url: ${{ secrets.SERVER_NAME }}
          user: ${{ secrets.USERNAME}}
          password: ${{ secrets.PASSWORD}}
          locations: /db-migrations
          command: info
          table: version_history

      - name: flyway mig
        uses: ./.github/actions/flyway
        with: 
          url: ${{ secrets.SERVER_NAME }}
          user: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          locations: /db-migrations/developers
          command: migrate
          table: version_history